import type { Metadata } from "next";
import "./fonts.css";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="" cz-shortcut-listen="true">
        <Providers>
          <Header />
          <div className="content-area">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
